
worker: 10.23.42.40:22345

mysqlcommand : ["./osv.sh", "../../blobs/whole_system/mine_cinrunq3_v0.24-533-g1d3b2595.img", "2-7", "--stage.max_assignment_age=20000000 --idle_mwait=0"]
perfcommand: ["bash", "-c", "sleep 30d"]

tpcc:
    seconds: 40
    terminals: 25
    scalefactor: 2
    mysql:
        host: 10.23.42.10
        port: 3306
        user: root
        password: ""
        db: tpcc
