
worker: 10.23.42.40:22345

mysqlcommand : ["./linuxvm.sh", "../../blobs/whole_system/linuxvm.img", "2-7"]
perfcommand: ["bash", "-c", "sleep 30d"]

tpcc:
    seconds: 40
    terminals: 60
    scalefactor: 2
    mysql:
        host: 10.23.42.10
        port: 3306
        user: root
        password: ""
        db: tpcc
